name: Film Converter

on: 
  release:
    types: [published]
  push:
    tags:
    - 'v*'
  #  branches: 
  #    - master
  schedule:
    - cron: '12 */6 * * *'
  watch:
    types: [started]
   
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requests #安装requests
      run: |
        pip install requests
    - name: Read config from secrets  #读取机密
      env: 
        CONFIG_REMOTE: ${{ secrets.CONFIG_REMOTE }} # secrets_id 提供
      run: | 
        sudo apt install curl ffmpeg
        curl https://rclone.org/install.sh | sudo bash
        echo -e $CONFIG_REMOTE > rclone.conf
        rclone --config="rclone.conf" listremotes 
    - name: START
      run: | 
        python converter.py